class AddProjects < ActiveRecord::Migration
  def up
#Graphic
  	Project.create(:title => "Winter Warmer Pack",:client => "Red Cross",:date_added => "2012",:brief => "password",:solution => "password",:outcome => "text",:is_featured => true,:is_published => false,:project_type => "0")
    Project.create(:title => "Various",:client => "IHC",:date_added => "2012",:brief => "password",:solution => "password",:outcome => "text",:is_featured => false,:is_published => false,:project_type => "0") 
	Project.create(:title => "Journeys In National Parks",:client => "Natural History New Zealand",:date_added => "2011",:brief => "To design a DVD menu for NHNZ's 25th Anniversary of Journeys In National Parks. Scans of old projector slides were provided to use as the central image.",:solution => "The koru slide was selected for its curved shapes which lended itself well to the NHNZ DVD template.",:outcome => "Manager Caroline Cook was delighted with the final DVD menu She asked for several more slides to be cleaned up for use on the DVD slick. Journeys In National Parks in now on sale at the NHNZ website and Marbecks stores.",:is_featured =>false,:is_published => false,:project_type => 0)
    Project.create(:title => "Greenscape Pop Up Covers & Growhouses",:client => "Highland Distributors",:date_added => "2011", :brief => "To develop the company's existing template for their range of pop up covers and growhouses.",:solution => "while I was given clear specifications I had to convince the client I was capable of creating two templates that could be used across multiple dimensions, and subtley photoshop the images to draw maximum attention.",:outcome => "by keeping in constant contact with the client throughout the design process I have succeeded in securing future work with the studio and trust sales will go well at the Warehouse and Mitre 10.",:is_featured => false,:is_published => false,:project_type => 0)
    Project.create(:title => "Peggydale",:client => "Peggydale",:date_added => "2011",:brief => "To continue Leanne Preston's rebrand of Peggydale cafe and giftshop. The rebrand includes a new logo for business cards, gift bags,  and road sign.",:solution => "the logo has incorporated themes of rural life, tourism and high quality fashion. The final logo features a mannaquin encircled in number eight wire in rich, warm colours so as can be seen on the road sign in the country.",:outcome => "Owners Mervyn and Alison are very excited about their new look and hope visitors stopping by will feel the same.",:is_featured => false,:is_published => false,:project_type => 0)
    Project.create(:title => "Brochures and Advertisements",:client => "FIEA",:date_added => "2011",:brief => "To follow and further adapt the style and templates of each event in order to design cohesive brochures and advertisements for web and print.",:solution => "I have raised the expectations of the FIEA's visual look. The advertisements certainly stand out amongst magazine pages. Brent Apthorp of the Dunedin branch said the Wood Preservation cover was the best one they have had in the past ten years.",:outcome => "",:is_featured => false,:is_published => false,:project_type => 0)
    Project.create(:title => "Micro-Archtecture,Student Projects and Simple Retrofits",:client => "Tim Bishop, SHAC",:date_added => "2011",:brief => "To design a poster that would attract eco-conscious people in the 18 - 35 year age bracket to attend this symposium.",:solution => "A clean, minimalistic poster using an image supplied that illustrates the beauty of Micro-Architecture. This style works with  the Micro-Architecture blog.",:outcome => " The poster attracted a small amount of people and had a a great time. Since doing this poster Tim has had me continue edtiting photos and preparing them for the Micro-Architecture blog.",:is_featured => false,:is_published => false,:project_type => 0)
    Project.create(:title => "H Block 6th Floor Foyer Graphics",:client => "Otago Polytechnic's School of Midwifery, Social Services and Massage Clinic",:date_added => "2010",:brief => "In teams of two create a series of environmental graphics that reflect the learning environment of each floor of H block at Otago Polytechnic. Alice Berry and I worked on the 6th floor, which has the School of Midwifery, Social Services and the Massage Clinic.",:solution => " Four illustrations were hand drawn and pentooled in Adobe Illustrator for the institute's Roland vinyl printer. These images reflect the calm learning environment and support the developing wayfinding system and existing water fountain and fire hose.",:outcome => "the students and staff of the School of Midwifery, the School of Social Services and the Massage Clinic were all very excited to see their newly decorated floor. These images say that students here learn to make connections with their head and their hands.",:is_featured => false,:is_published => false,:project_type => 1)
    Project.create(:title => "FAR 2 kwik",:client => "self directed",:date_added => "2010",:brief => "To create a series of four images based on Fernando Sorrentino's The Ushuaia Rabbit.",:solution => "To explore and develop new methods of illustration that capture the energy and emotion in this short story.",:outcome => "four illustrations were created using a mix of watercolour, indian ink, chalk and contae and composited in Adobe Photoshop. While the muted colour palette has a sense of melancholy, it also makes the rabbit's plight even sweeter.",:is_featured => true,:is_published => false,:project_type => 1)
    Project.create(:title => "Logo, Stamp and Interpretive Panel",:client => "Historic Iona Church Restoration Trust",:date_added => "2010",:brief => "To design a logo and an interpretive panel for the Historic Iona Church Restoration Trust.",:solution => "Develop exciting panels to encourage public awareness. Text was developed and photographs were taken of the historic church. These were used in the design of the interpretive panel to be displayed in Port Chalmers.",:outcome => "These panels have been printed on permanent materials for display at both Iona Church and the Public Library at Port Chalmers. The trust use the letterhead and stamp and are very happy with the identity and communication outcomes.",:is_featured => false,:is_published => true,:project_type => 0)
#Illustration
  	Project.create(:title => 'The Majestic Sea Unicorn',:client => 'self directed',:date_added => 2012,:brief => 'password',:solution => 'password',:outcome => 'text',:is_featured => false,:is_published => false,:project_type => 1)
	Project.create(:title => 'Banana Giraffe',:client => 'self directed',:date_added => 2012 ,:brief => 'password',:solution => 'password',:outcome => 'text',:is_featured => true,:is_published => false,:project_type => 1)
	Project.create(:title => 'Damn Stupid Idea',:client => 'self directed',:date_added => 2012 ,:brief => 'password',:solution => 'password',:outcome => 'text',:is_featured => false,:is_published => false, :project_type => 1)
	Project.create(:title => 'Goregonite Old Pucks ',:client => 'Mike Farley',:date_added => 2011 ,:brief => 'To redesign the logo of the Goregonite Old Pucks hockey team jersey. This design will then be sent to America to be printed professionally.',:solution => 'An illustration of a bear puck-shooting a beer can is metaphoric of the grizzly old men in the team.',:outcome => 'The team are so pleased with the design that they are now envisioning decking out the team van in time for South Island wide ice hockey tournaments.',:is_featured => false,:is_published => false,:project_type => 1)
	Project.create(:title => 'Golf Rankings',:client => 'Kiwi Dreams',:date_added => 2011 ,:brief => 'To illustrate a golf flag that could be used on the header of golfrankings.co.nz and be incorporated into a certificate to be displayed in all the website\'s featured golf courses.',:solution => 'The illustrated golf flag includes a flax bush which incorporates New Zealand\'s natural beauty. The white flax bush also looks like a bunker has been hit, showing these are active golf courses.',:outcome => 'This illustration was quickly incoporated into golfrankings.co.nz\'s new website and is now available to view on the internet.',:is_featured => false,:is_published => false,:project_type => 1)
	Project.create(:title => 'Love Christchurch',:client => 'self directed',:date_added => 2011 ,:brief => 'To design a simple image that could be used as a fundraiser to help Christchurch\'s recovery from the devastating earthquakes.',:solution => ' Jagged lines echo the cathedral\'s steeple show the many tremors plaguing the city but the heart shape reminds them we are thinking of them. Indian ink was used for its unpridictable nature.',:outcome => 'Copies of this image were printed on 160 gsm matt paper and secretly posted to old friends in Christchurch who were both delighted and surprised.',:is_featured => false,:is_published => false,:project_type => 1)
	Project.create(:title => 'Foundation Fingertips',:client => 'self directed',:date_added => 2011 ,:brief => 'To illustrate a set of letters based on the song Foundations by British pop singer Kate Nash.',:solution => 'My own fingers were photographed in different poses, then drawn taking features from each photograph. These letters were then traced over with indian ink.',:outcome => 'not sure yet',:is_featured => false,:is_published => false,:project_type => 1)
	Project.create(:title => 'H Block 6th Floor Foyer Graphics',:client => 'Otago Polytechnic\'s School of Midwifery, Social Services and Massage Clinic',:date_added => 2010 ,:brief => 'In teams of two create a series of environmental graphics that reflect the learning environment of each floor of H block at Otago Polytechnic. Alice Berry and I worked on the 6th floor, which has the School of Midwifery, Social Services and the Massage Clinic.',:solution => ' Four illustrations were hand drawn and pentooled in Adobe Illustrator for the institute’s Roland vinyl printer. These images reflect the calm learning environment and support the developing wayfinding system and existing water fountain and fire hose.',:outcome => 'the students and staff of the School of Midwifery, the School of Social Services and the Massage Clinic were all very excited to see their newly decorated floor. These images say that students here learn to make connections with their head and their hands.',:is_featured => false,:is_published => false,:project_type => 1)
	Project.create(:title => 'The Ushuaia Rabbit',:client => 'self directed',:date_added => 2010 ,:brief => 'To create a series of four images based on Fernando Sorrentino’s The Ushuaia Rabbit.',:solution => 'To explore and develop new methods of illustration that capture the energy and emotion in this short story.',:outcome => 'four illustrations were created using a mix of watercolour, indian ink, chalk and contae and composited inAdobe Photoshop. While the muted colour palette has a sense of melancholy, it also makes the rabbit’s plight even sweeter.',:is_featured => true,:is_published => false,:project_type => 1)
	Project.create(:title => 'New Zealand Flavoured Christmas cards',:client => 'self directed',:date_added => 2009 ,:brief => 'In a team with Sarah Anderson and Letitia Margalski, design two New Zealand Christmas cards each, packaging and order forms to sell to local businesses and at the Student Showcase in November. I illustrated the Pavolva and Pohutakawa cards.',:solution => 'These cards take the traditional Christmas colours of red, green and gold naturally occuring in iconic kiwiana Pohutakawa and pavlova to create sophisticated New Zealand Christmas cards.',:outcome => 'The cards were extrmely popular with sales in both box sets and individual card orders, particularly in the pavlova design.',:is_featured => false,:is_published => false,:project_type => 1)
 # Misc
  	Project.create(:title => 'Dirty Threads',:client => 'self directed',:date_added => 2009 ,:brief => 'A three week knitting class had students design a workable knitting pattern either using contemporary, traditional or non-knit inspiration for hand knitters.',:solution => 'Dirty Threads, a play on the nickname Dirty Dreads, is a more obscene take on the traditional, chubby knitted doll. In his story Dirty Threads discovers that the more intensely he plays his guitar, the more he unravels, and he must sew himself together again.',:outcome => 'Dirty Threads\' grunge musician attitude and ready for action ensemble, complete with a knitted guitar, removable shirt and rollable jeans, has sparked an enthusiasm amongst Dunedin youth and similar dolls have been requested.',:is_featured => false,:is_published => false,:project_type => 2)
	Project.create(:title => 'Life Has No Control Z',:client => 'self directed', :date_added => 2009 ,:brief => 'Tto create a book jacket or design outcome for a literature review covering a contemporary issue in design. My literature review Hand Craft vs Technology explored how these two methods of craftsmanship affect each other and what classes good design today.',:solution => 'A quote from William Morris, instigator of the Arts and Crafts movement in the Industrial Revolution,  has been set in a digital looking typeface, projected onto card and half stiched by hand. This quote is as relevant today as it was 150 years ago.',:outcome => 'Ahand stitched quote that would once have been described as lazy and unfinished, is today hailed for its quirks and  imperfections in our flawless, digital world.',:is_featured => false,:is_published => false,:project_type => 2)
  end

  def down
  end
end
